gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/big-int.c -o /home/user/project.m/lib.core/big-int.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/object.c -o /home/user/project.m/lib.core/object.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/defines.c -o /home/user/project.m/lib.core/defines.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/threads.c -o /home/user/project.m/lib.core/threads.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/combinations.c -o /home/user/project.m/lib.core/combinations.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/tree.c -o /home/user/project.m/lib.core/tree.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/print.c -o /home/user/project.m/lib.core/print.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/topological.c -o /home/user/project.m/lib.core/topological.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/permute.c -o /home/user/project.m/lib.core/permute.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/file-writer.c -o /home/user/project.m/lib.core/file-writer.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/convert.c -o /home/user/project.m/lib.core/convert.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/memory.c -o /home/user/project.m/lib.core/memory.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/stopwatch.c -o /home/user/project.m/lib.core/stopwatch.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/random.c -o /home/user/project.m/lib.core/random.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/ascii.c -o /home/user/project.m/lib.core/ascii.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/tainio-tree.c -o /home/user/project.m/lib.core/tainio-tree.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/file-reader.c -o /home/user/project.m/lib.core/file-reader.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/string.c -o /home/user/project.m/lib.core/string.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/threads-signal.c -o /home/user/project.m/lib.core/threads-signal.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/error.c -o /home/user/project.m/lib.core/error.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/list.c -o /home/user/project.m/lib.core/list.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/file.c -o /home/user/project.m/lib.core/file.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/threads-lock.c -o /home/user/project.m/lib.core/threads-lock.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.core/hash.c -o /home/user/project.m/lib.core/hash.o
ar rsc /home/user/project.m/lib.core/lib.core.a /home/user/project.m/lib.core/big-int.o /home/user/project.m/lib.core/object.o /home/user/project.m/lib.core/defines.o /home/user/project.m/lib.core/threads.o /home/user/project.m/lib.core/combinations.o /home/user/project.m/lib.core/tree.o /home/user/project.m/lib.core/print.o /home/user/project.m/lib.core/topological.o /home/user/project.m/lib.core/permute.o /home/user/project.m/lib.core/file-writer.o /home/user/project.m/lib.core/convert.o /home/user/project.m/lib.core/memory.o /home/user/project.m/lib.core/stopwatch.o /home/user/project.m/lib.core/random.o /home/user/project.m/lib.core/ascii.o /home/user/project.m/lib.core/tainio-tree.o /home/user/project.m/lib.core/file-reader.o /home/user/project.m/lib.core/string.o /home/user/project.m/lib.core/threads-signal.o /home/user/project.m/lib.core/error.o /home/user/project.m/lib.core/list.o /home/user/project.m/lib.core/file.o /home/user/project.m/lib.core/threads-lock.o /home/user/project.m/lib.core/hash.o 
ranlib /home/user/project.m/lib.core/lib.core.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.app/arguments-validate.c -o /home/user/project.m/lib.app/arguments-validate.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.app/arguments-usage.c -o /home/user/project.m/lib.app/arguments-usage.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.app/events.c -o /home/user/project.m/lib.app/events.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.app/arguments-default.c -o /home/user/project.m/lib.app/arguments-default.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.app/arguments.c -o /home/user/project.m/lib.app/arguments.o
ar rsc /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.app/arguments-validate.o /home/user/project.m/lib.app/arguments-usage.o /home/user/project.m/lib.app/events.o /home/user/project.m/lib.app/arguments-default.o /home/user/project.m/lib.app/arguments.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.app/lib.app.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.test/test.c -o /home/user/project.m/lib.test/test.o
ar rsc /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.test/test.o /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.test/lib.test.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.encode/encode.c -o /home/user/project.m/lib.encode/encode.o
ar rsc /home/user/project.m/lib.encode/lib.encode.a /home/user/project.m/lib.encode/encode.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.encode/lib.encode.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.encode/test-encode.c -o /home/user/project.m/app.test.lib.encode/test-encode.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.encode/test-encode.o /home/user/project.m/app.test.lib.encode/test.o /home/user/project.m/lib.encode/lib.encode.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.encode/app.test.lib.encode -lm -ldl -lssl -lcrypto 1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.graphics/colors.c -o /home/user/project.m/lib.graphics/colors.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.graphics/structures.c -o /home/user/project.m/lib.graphics/structures.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.graphics/canvas.c -o /home/user/project.m/lib.graphics/canvas.o
ar rsc /home/user/project.m/lib.graphics/lib.graphics.a /home/user/project.m/lib.graphics/colors.o /home/user/project.m/lib.graphics/structures.o /home/user/project.m/lib.graphics/canvas.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.graphics/lib.graphics.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.graphics/test-canvas.c -o /home/user/project.m/app.test.lib.graphics/test-canvas.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.graphics/test.o /home/user/project.m/app.test.lib.graphics/test-canvas.o /home/user/project.m/lib.graphics/lib.graphics.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.graphics/app.test.lib.graphics -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.client/client.c -o /home/user/project.m/lib.net.client/client.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.client/client-epoll.c -o /home/user/project.m/lib.net.client/client-epoll.o
ar rsc /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.net.client/client.o /home/user/project.m/lib.net.client/client-epoll.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.net.client/lib.net.client.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker-close.c -o /home/user/project.m/lib.net.poll/worker-close.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker-internal-close.c -o /home/user/project.m/lib.net.poll/worker-internal-close.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker.c -o /home/user/project.m/lib.net.poll/worker.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker-write.c -o /home/user/project.m/lib.net.poll/worker-write.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/poll.c -o /home/user/project.m/lib.net.poll/poll.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/events.c -o /home/user/project.m/lib.net.poll/events.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker-read.c -o /home/user/project.m/lib.net.poll/worker-read.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/queue.c -o /home/user/project.m/lib.net.poll/queue.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.poll/worker-internal-monitor.c -o /home/user/project.m/lib.net.poll/worker-internal-monitor.o
ar rsc /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.net.poll/worker-close.o /home/user/project.m/lib.net.poll/worker-internal-close.o /home/user/project.m/lib.net.poll/worker.o /home/user/project.m/lib.net.poll/worker-write.o /home/user/project.m/lib.net.poll/poll.o /home/user/project.m/lib.net.poll/events.o /home/user/project.m/lib.net.poll/worker-read.o /home/user/project.m/lib.net.poll/queue.o /home/user/project.m/lib.net.poll/worker-internal-monitor.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.net.poll/lib.net.poll.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.server/server-epoll.c -o /home/user/project.m/lib.net.server/server-epoll.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.server/server.c -o /home/user/project.m/lib.net.server/server.o
ar rsc /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.server/server-epoll.o /home/user/project.m/lib.net.server/server.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.net.server/lib.net.server.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-internal-loop.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-internal-loop.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-1.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-write-1.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-write-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-write-3.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-write-3.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-queue.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-queue.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll.c -o /home/user/project.m/app.test.lib.net.poll/test-poll.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-close-1.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-close-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-on-close.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-on-close.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-write-2.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-write-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-close-2.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-close-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-2.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-2.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-events.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-events.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-1.c -o /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-1.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.net.poll/test-poll-internal-loop.o /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-1.o /home/user/project.m/app.test.lib.net.poll/test-poll-write-1.o /home/user/project.m/app.test.lib.net.poll/test-poll-write-3.o /home/user/project.m/app.test.lib.net.poll/test-poll-queue.o /home/user/project.m/app.test.lib.net.poll/test-poll.o /home/user/project.m/app.test.lib.net.poll/test-poll-close-1.o /home/user/project.m/app.test.lib.net.poll/test-poll-on-close.o /home/user/project.m/app.test.lib.net.poll/test.o /home/user/project.m/app.test.lib.net.poll/test-poll-write-2.o /home/user/project.m/app.test.lib.net.poll/test-poll-close-2.o /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-2.o /home/user/project.m/app.test.lib.net.poll/test-poll-monitor-2.o /home/user/project.m/app.test.lib.net.poll/test-poll-events.o /home/user/project.m/app.test.lib.net.poll/test-poll-on-read-1.o /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.net.poll/app.test.lib.net.poll -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.random.number/main.c -o /home/user/project.m/app.random.number/main.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.random.number/main.o /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.random.number/app.random.number -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.server/test-server-on-connect.c -o /home/user/project.m/app.test.lib.net.server/test-server-on-connect.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.server/test-server.c -o /home/user/project.m/app.test.lib.net.server/test-server.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.net.server/test-server-on-connect.o /home/user/project.m/app.test.lib.net.server/test-server.o /home/user/project.m/app.test.lib.net.server/test.o /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.net.server/app.test.lib.net.server -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.compile/compile-link.c -o /home/user/project.m/lib.compile/compile-link.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.compile/compile-print.c -o /home/user/project.m/lib.compile/compile-print.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.compile/compile-project.c -o /home/user/project.m/lib.compile/compile-project.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.compile/compile-action.c -o /home/user/project.m/lib.compile/compile-action.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.compile/compile.c -o /home/user/project.m/lib.compile/compile.o
ar rsc /home/user/project.m/lib.compile/lib.compile.a /home/user/project.m/lib.compile/compile-link.o /home/user/project.m/lib.compile/compile-print.o /home/user/project.m/lib.compile/compile-project.o /home/user/project.m/lib.compile/compile-action.o /home/user/project.m/lib.compile/compile.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.compile/lib.compile.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.compile/test-compile-project.c -o /home/user/project.m/app.test.lib.compile/test-compile-project.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.compile/test-compile.c -o /home/user/project.m/app.test.lib.compile/test-compile.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.compile/test-compile-project.o /home/user/project.m/app.test.lib.compile/test-compile.o /home/user/project.m/app.test.lib.compile/test.o /home/user/project.m/lib.compile/lib.compile.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.compile/app.test.lib.compile -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-tree.c -o /home/user/project.m/app.test.lib.core/test-tree.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-file.c -o /home/user/project.m/app.test.lib.core/test-file.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-string.c -o /home/user/project.m/app.test.lib.core/test-string.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-file-writer.c -o /home/user/project.m/app.test.lib.core/test-file-writer.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-memory.c -o /home/user/project.m/app.test.lib.core/test-memory.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-convert.c -o /home/user/project.m/app.test.lib.core/test-convert.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-topological.c -o /home/user/project.m/app.test.lib.core/test-topological.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-defines.c -o /home/user/project.m/app.test.lib.core/test-defines.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-random.c -o /home/user/project.m/app.test.lib.core/test-random.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-big-int.c -o /home/user/project.m/app.test.lib.core/test-big-int.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-stopwatch.c -o /home/user/project.m/app.test.lib.core/test-stopwatch.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-print.c -o /home/user/project.m/app.test.lib.core/test-print.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-list.c -o /home/user/project.m/app.test.lib.core/test-list.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-error.c -o /home/user/project.m/app.test.lib.core/test-error.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-permute.c -o /home/user/project.m/app.test.lib.core/test-permute.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-object.c -o /home/user/project.m/app.test.lib.core/test-object.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-threads.c -o /home/user/project.m/app.test.lib.core/test-threads.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-file-reader.c -o /home/user/project.m/app.test.lib.core/test-file-reader.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-combinations.c -o /home/user/project.m/app.test.lib.core/test-combinations.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-ascii.c -o /home/user/project.m/app.test.lib.core/test-ascii.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core/test-tainio-tree.c -o /home/user/project.m/app.test.lib.core/test-tainio-tree.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.core/test-tree.o /home/user/project.m/app.test.lib.core/test-file.o /home/user/project.m/app.test.lib.core/test-string.o /home/user/project.m/app.test.lib.core/test-file-writer.o /home/user/project.m/app.test.lib.core/test-memory.o /home/user/project.m/app.test.lib.core/test-convert.o /home/user/project.m/app.test.lib.core/test-topological.o /home/user/project.m/app.test.lib.core/test-defines.o /home/user/project.m/app.test.lib.core/test.o /home/user/project.m/app.test.lib.core/test-random.o /home/user/project.m/app.test.lib.core/test-big-int.o /home/user/project.m/app.test.lib.core/test-stopwatch.o /home/user/project.m/app.test.lib.core/test-print.o /home/user/project.m/app.test.lib.core/test-list.o /home/user/project.m/app.test.lib.core/test-error.o /home/user/project.m/app.test.lib.core/test-permute.o /home/user/project.m/app.test.lib.core/test-object.o /home/user/project.m/app.test.lib.core/test-threads.o /home/user/project.m/app.test.lib.core/test-file-reader.o /home/user/project.m/app.test.lib.core/test-combinations.o /home/user/project.m/app.test.lib.core/test-ascii.o /home/user/project.m/app.test.lib.core/test-tainio-tree.o /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.core/app.test.lib.core -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.plugin/plugin.c -o /home/user/project.m/lib.plugin/plugin.o
ar rsc /home/user/project.m/lib.plugin/lib.plugin.a /home/user/project.m/lib.plugin/plugin.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.plugin/lib.plugin.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.plugin/test-plugin.c -o /home/user/project.m/app.test.lib.plugin/test-plugin.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.plugin/test-plugin.o /home/user/project.m/app.test.lib.plugin/test.o /home/user/project.m/lib.plugin/lib.plugin.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.plugin/app.test.lib.plugin -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/plugin.display.sdl/plugin.c -o /home/user/project.m/plugin.display.sdl/plugin.o
gcc -lrt -shared /home/user/project.m/plugin.display.sdl/plugin.o /home/user/project.m/lib.graphics/lib.graphics.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/plugin.display.sdl/plugin.display.sdl.so -lm -lSDL2 -lX11  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.stream/connection.c -o /home/user/project.m/lib.net.stream/connection.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.stream/task-queue.c -o /home/user/project.m/lib.net.stream/task-queue.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.stream/connection-queue.c -o /home/user/project.m/lib.net.stream/connection-queue.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.stream/stream.c -o /home/user/project.m/lib.net.stream/stream.o
ar rsc /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.stream/connection.o /home/user/project.m/lib.net.stream/task-queue.o /home/user/project.m/lib.net.stream/connection-queue.o /home/user/project.m/lib.net.stream/stream.o /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.net.stream/lib.net.stream.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.websocket/http.c -o /home/user/project.m/lib.net.websocket/http.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.websocket/frame.c -o /home/user/project.m/lib.net.websocket/frame.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.net.websocket/websocket.c -o /home/user/project.m/lib.net.websocket/websocket.o
ar rsc /home/user/project.m/lib.net.websocket/lib.net.websocket.a /home/user/project.m/lib.net.websocket/http.o /home/user/project.m/lib.net.websocket/frame.o /home/user/project.m/lib.net.websocket/websocket.o /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.encode/lib.encode.a /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.net.websocket/lib.net.websocket.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.websocket/main.c -o /home/user/project.m/app.websocket/main.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.websocket/server.c -o /home/user/project.m/app.websocket/server.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.websocket/main.o /home/user/project.m/app.websocket/server.o /home/user/project.m/lib.net.websocket/lib.net.websocket.a /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.encode/lib.encode.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.websocket/app.websocket -lm -ldl -lssl -lcrypto 1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.compile/main.c -o /home/user/project.m/app.compile/main.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.compile/main.o /home/user/project.m/lib.compile/lib.compile.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.compile/app.compile -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.stream/test-write-close.c -o /home/user/project.m/app.test.lib.net.stream/test-write-close.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.stream/test-add.c -o /home/user/project.m/app.test.lib.net.stream/test-add.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.stream/test-stream.c -o /home/user/project.m/app.test.lib.net.stream/test-stream.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.stream/test-write.c -o /home/user/project.m/app.test.lib.net.stream/test-write.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.net.stream/test-write-close.o /home/user/project.m/app.test.lib.net.stream/test-add.o /home/user/project.m/app.test.lib.net.stream/test.o /home/user/project.m/app.test.lib.net.stream/test-stream.o /home/user/project.m/app.test.lib.net.stream/test-write.o /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.net.stream/app.test.lib.net.stream -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-path.c -o /home/user/project.m/lib.pattern/pattern-path.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-branch.c -o /home/user/project.m/lib.pattern/pattern-branch.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-search.c -o /home/user/project.m/lib.pattern/pattern-search.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-whitespace.c -o /home/user/project.m/lib.pattern/pattern-whitespace.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-token.c -o /home/user/project.m/lib.pattern/pattern-token.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.pattern/pattern-path-match.c -o /home/user/project.m/lib.pattern/pattern-path-match.o
ar rsc /home/user/project.m/lib.pattern/lib.pattern.a /home/user/project.m/lib.pattern/pattern-path.o /home/user/project.m/lib.pattern/pattern-branch.o /home/user/project.m/lib.pattern/pattern-search.o /home/user/project.m/lib.pattern/pattern-whitespace.o /home/user/project.m/lib.pattern/pattern-token.o /home/user/project.m/lib.pattern/pattern-path-match.o /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.pattern/lib.pattern.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-whitespace.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-whitespace.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-token.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-token.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-path.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-path.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-branch.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-branch.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-path-match.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-path-match.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.pattern/test-pattern-search.c -o /home/user/project.m/app.test.lib.pattern/test-pattern-search.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.pattern/test-pattern-whitespace.o /home/user/project.m/app.test.lib.pattern/test.o /home/user/project.m/app.test.lib.pattern/test-pattern-token.o /home/user/project.m/app.test.lib.pattern/test-pattern-path.o /home/user/project.m/app.test.lib.pattern/test-pattern-branch.o /home/user/project.m/app.test.lib.pattern/test-pattern-path-match.o /home/user/project.m/app.test.lib.pattern/test-pattern-search.o /home/user/project.m/lib.pattern/lib.pattern.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.pattern/app.test.lib.pattern -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.bench.lib.net/client.c -o /home/user/project.m/app.bench.lib.net/client.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.bench.lib.net/main.c -o /home/user/project.m/app.bench.lib.net/main.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.bench.lib.net/server.c -o /home/user/project.m/app.bench.lib.net/server.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.bench.lib.net/client.o /home/user/project.m/app.bench.lib.net/main.o /home/user/project.m/app.bench.lib.net/server.o /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.bench.lib.net/app.bench.lib.net -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-frame.c -o /home/user/project.m/app.test.lib.net.websocket/test-frame.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-1.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-5.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-5.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-http.c -o /home/user/project.m/app.test.lib.net.websocket/test-http.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-4.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-4.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-3.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-3.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-connect-error.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-connect-error.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-1.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-add.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-2.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-1.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-1.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-2.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-2.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-2.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-3.c -o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-3.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.net.websocket/test-frame.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-1.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-5.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade.o /home/user/project.m/app.test.lib.net.websocket/test-http.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-4.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-3.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-connect-error.o /home/user/project.m/app.test.lib.net.websocket/test.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-1.o /home/user/project.m/app.test.lib.net.websocket/test-websocket.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-2.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-add-error-1.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-2.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-upgrade-2.o /home/user/project.m/app.test.lib.net.websocket/test-websocket-http-on-read-3.o /home/user/project.m/lib.net.websocket/lib.net.websocket.a /home/user/project.m/lib.net.stream/lib.net.stream.a /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.poll/lib.net.poll.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.encode/lib.encode.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.net.websocket/app.test.lib.net.websocket -lm -ldl -lssl -lcrypto 1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.app/test-arguments.c -o /home/user/project.m/app.test.lib.app/test-arguments.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.app/test-arguments-usage.c -o /home/user/project.m/app.test.lib.app/test-arguments-usage.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.app/test-arguments-validate.c -o /home/user/project.m/app.test.lib.app/test-arguments-validate.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.app/test-events.o /home/user/project.m/app.test.lib.app/test-arguments.o /home/user/project.m/app.test.lib.app/test-arguments-usage.o /home/user/project.m/app.test.lib.app/test.o /home/user/project.m/app.test.lib.app/test-arguments-validate.o /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.app/app.test.lib.app -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.pattern.replace/main.c -o /home/user/project.m/app.pattern.replace/main.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.pattern.replace/main.o /home/user/project.m/lib.pattern/lib.pattern.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.pattern.replace/app.pattern.replace -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.client/test-client-on-connect-error.c -o /home/user/project.m/app.test.lib.net.client/test-client-on-connect-error.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.client/test-client-on-connect.c -o /home/user/project.m/app.test.lib.net.client/test-client-on-connect.o
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.net.client/test-client.c -o /home/user/project.m/app.test.lib.net.client/test-client.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.net.client/test.o /home/user/project.m/app.test.lib.net.client/test-client-on-connect-error.o /home/user/project.m/app.test.lib.net.client/test-client-on-connect.o /home/user/project.m/app.test.lib.net.client/test-client.o /home/user/project.m/lib.net.server/lib.net.server.a /home/user/project.m/lib.net.client/lib.net.client.a /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.net.client/app.test.lib.net.client -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.pattern.search/main.c -o /home/user/project.m/app.pattern.search/main.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.pattern.search/main.o /home/user/project.m/lib.pattern/lib.pattern.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.pattern.search/app.pattern.search -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/lib.display.plugin/display-plugin.c -o /home/user/project.m/lib.display.plugin/display-plugin.o
ar rsc /home/user/project.m/lib.display.plugin/lib.display.plugin.a /home/user/project.m/lib.display.plugin/display-plugin.o /home/user/project.m/lib.plugin/lib.plugin.a /home/user/project.m/lib.graphics/lib.graphics.a /home/user/project.m/lib.core/lib.core.a 
ranlib /home/user/project.m/lib.display.plugin/lib.display.plugin.a
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.drawing/main.c -o /home/user/project.m/app.drawing/main.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.drawing/main.o /home/user/project.m/lib.display.plugin/lib.display.plugin.a /home/user/project.m/lib.plugin/lib.plugin.a /home/user/project.m/lib.graphics/lib.graphics.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.drawing/app.drawing -lm -ldl  1>/dev/null
gcc -std=gnu99 -O0 -pedantic -g -Wall -Wextra -Wconversion -Wformat-security -Werror -fPIC -I/home/user/project.m -c /home/user/project.m/app.test.lib.core.threadwait/test-threads.c -o /home/user/project.m/app.test.lib.core.threadwait/test-threads.o
gcc -pthread -lrt -rdynamic /home/user/project.m/app.test.lib.core.threadwait/test.o /home/user/project.m/app.test.lib.core.threadwait/test-threads.o /home/user/project.m/lib.test/lib.test.a /home/user/project.m/lib.app/lib.app.a /home/user/project.m/lib.core/lib.core.a -O0 -o /home/user/project.m/app.test.lib.core.threadwait/app.test.lib.core.threadwait -lm -ldl  1>/dev/null
